### ISSUE TITLE
Write tests for Staff.replaceMeasureAtIndex

### ISSUE THREAD

**Issue by drumnkyle** [drumnkyle/music-notation-swift#10]
There are no tests written for `Staff.replaceMeasureAtIndex` and there is not full code coverage.

**Comment by drumnkyle** [comment]
@robtimp if you'd like another task. This would be good for you to do. Comment back on this if you pick it up, so one of us doesn't.

**Comment by robtimp** [comment]
@drumnkyle Ok, I’m about to start on this.

**Comment by drumnkyle** [comment]
Great! Thanks man.
