### ISSUE TITLE
Add triple and quadruple dot

### ISSUE THREAD

**Issue by drumnkyle** [drumnkyle/music-notation-swift#34]
There is a such thing as a triple dot. So, need to just add one more case to the `Dot` enum.

**Comment by robtimp** [comment]
Though rare, there are some cases of quadruple dots in the standard repertoire, too: http://homes.soic.indiana.edu/donbyrd/CMNExtremes.htm

**Comment by robtimp** [comment]
@drumnkyle This raises a larger question, though: what use cases do you intend to cover with this library? Just fairly standard usage, less common cases, or somewhere in between?

For example, I feel like we should probably at least add support for alto and tenor clefs, which are quite common, but do we add soprano clef, for instance?

**Comment by drumnkyle** [comment]
Sheez. Quadruple?? Ok we can add that too. 

Yeah, that is a good question. Originally I was setting out to make something that can do everything. Now, I'm seeing everything can get pretty ridiculous.

Therefore, the main goal was to make a library that can support any kind of music app people will want to make on iOS, Mac, and (contingent on Swift support) Android, Windows, Linux, etc. 

So, my idea is to cover as much as we can. Seems like a quadruple dot is easy enough to add in, and I've been going through Tuplets and have finally gotten everything I can find. But yeah, at some point we will have to just not implement some things I guess.

**Comment by drumnkyle** [comment]
Is the number of dots arbitrary where we should just make it a count?

**Comment by robtimp** [comment]
@drumnkyle That makes sense to me
