### ISSUE TITLE
Support cut time

### ISSUE THREAD

**Issue by drumnkyle** [drumnkyle/music-notation-swift#53]

**Comment by robtimp** [comment]
What needs to be added for this? Isn't `TimeSignature(topNumber: 2, bottomNumber: 2)` enough?

**Comment by drumnkyle** [comment]
I thought maybe there was something about cut time I didn't understand, because there were so many other things that I underestimated and didn't realize there were so many edge cases. Sounds like maybe just for convenience we could make a `static` property for cut time and standard time if we want later. But for now, I will close this issue.
