### ISSUE TITLE
Enharmonic comparison for Tone

### ISSUE THREAD

**Issue by robtimp** [drumnkyle/music-notation-swift#77]
In addition to the current implementation of Equatable, which indicates whether two Tones are _semantically_ equivalent (i.e. they are both F#7, etc.), it would also be useful to have a method to check if two tones are enharmonically equivalent (i.e. F#7 and Gb7 have a different meaning, but the same sound).

**Comment by drumnkyle** [comment]
Good point. Absolutely. However, I would think this wouldn't be part of equatable. Rather, I suppose we would have a method called equivalent(to:) or something like that. Thoughts?

**Comment by robtimp** [comment]
Right. I didn't mean to suggest changing Equatable, but adding an additional method. My suggestion would be `enharmonic(with:)`.

**Comment by drumnkyle** [comment]
Yeah. That sounds good. Agreed.
